export interface PlayerStat {
  axis: string
  value: number
}

export interface Player {
  id: string
  player: string
  team: string
  position: "Goalkeeper" | "Defender" | "Midfielder" | "Forward"
  axes: PlayerStat[]
}

// Goalkeepers
export const goalkeepers: Player[] = [
  {
    id: "gk1",
    player: "Marc-André ter Stegen",
    team: "FC Barcelona",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 78.5 },
      { axis: "Clean Sheets", value: 65.0 },
      { axis: "Distribution Accuracy", value: 89.2 },
      { axis: "Sweeper Actions", value: 72.1 },
      { axis: "Cross Claims", value: 68.9 },
      { axis: "Long Passes", value: 81.4 },
      { axis: "Penalty Saves", value: 45.0 },
    ],
  },
  {
    id: "gk2",
    player: "Thibaut Courtois",
    team: "Real Madrid",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 82.1 },
      { axis: "Clean Sheets", value: 71.2 },
      { axis: "Distribution Accuracy", value: 85.7 },
      { axis: "Sweeper Actions", value: 69.8 },
      { axis: "Cross Claims", value: 74.3 },
      { axis: "Long Passes", value: 78.9 },
      { axis: "Penalty Saves", value: 60.0 },
    ],
  },
  {
    id: "gk3",
    player: "Alisson Becker",
    team: "Liverpool",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 79.8 },
      { axis: "Clean Sheets", value: 68.4 },
      { axis: "Distribution Accuracy", value: 91.3 },
      { axis: "Sweeper Actions", value: 85.2 },
      { axis: "Cross Claims", value: 71.6 },
      { axis: "Long Passes", value: 83.7 },
      { axis: "Penalty Saves", value: 55.0 },
    ],
  },
  {
    id: "gk4",
    player: "Ederson",
    team: "Manchester City",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 76.2 },
      { axis: "Clean Sheets", value: 72.8 },
      { axis: "Distribution Accuracy", value: 94.1 },
      { axis: "Sweeper Actions", value: 88.9 },
      { axis: "Cross Claims", value: 65.4 },
      { axis: "Long Passes", value: 87.2 },
      { axis: "Penalty Saves", value: 40.0 },
    ],
  },
  {
    id: "gk5",
    player: "Manuel Neuer",
    team: "Bayern Munich",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 80.7 },
      { axis: "Clean Sheets", value: 69.1 },
      { axis: "Distribution Accuracy", value: 88.6 },
      { axis: "Sweeper Actions", value: 91.4 },
      { axis: "Cross Claims", value: 76.8 },
      { axis: "Long Passes", value: 82.5 },
      { axis: "Penalty Saves", value: 65.0 },
    ],
  },
  {
    id: "gk6",
    player: "Gianluigi Donnarumma",
    team: "PSG",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 77.9 },
      { axis: "Clean Sheets", value: 66.7 },
      { axis: "Distribution Accuracy", value: 86.3 },
      { axis: "Sweeper Actions", value: 71.2 },
      { axis: "Cross Claims", value: 73.5 },
      { axis: "Long Passes", value: 79.8 },
      { axis: "Penalty Saves", value: 70.0 },
    ],
  },
  {
    id: "gk7",
    player: "Jan Oblak",
    team: "Atlético Madrid",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 84.3 },
      { axis: "Clean Sheets", value: 74.6 },
      { axis: "Distribution Accuracy", value: 83.1 },
      { axis: "Sweeper Actions", value: 67.4 },
      { axis: "Cross Claims", value: 69.2 },
      { axis: "Long Passes", value: 76.7 },
      { axis: "Penalty Saves", value: 50.0 },
    ],
  },
  {
    id: "gk8",
    player: "Hugo Lloris",
    team: "Tottenham",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 75.6 },
      { axis: "Clean Sheets", value: 62.3 },
      { axis: "Distribution Accuracy", value: 81.9 },
      { axis: "Sweeper Actions", value: 73.8 },
      { axis: "Cross Claims", value: 67.1 },
      { axis: "Long Passes", value: 74.2 },
      { axis: "Penalty Saves", value: 35.0 },
    ],
  },
  {
    id: "gk9",
    player: "Keylor Navas",
    team: "PSG",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 81.4 },
      { axis: "Clean Sheets", value: 67.9 },
      { axis: "Distribution Accuracy", value: 84.7 },
      { axis: "Sweeper Actions", value: 70.6 },
      { axis: "Cross Claims", value: 72.8 },
      { axis: "Long Passes", value: 77.3 },
      { axis: "Penalty Saves", value: 58.0 },
    ],
  },
  {
    id: "gk10",
    player: "David de Gea",
    team: "Manchester United",
    position: "Goalkeeper",
    axes: [
      { axis: "Save %", value: 79.2 },
      { axis: "Clean Sheets", value: 64.8 },
      { axis: "Distribution Accuracy", value: 82.4 },
      { axis: "Sweeper Actions", value: 68.7 },
      { axis: "Cross Claims", value: 70.5 },
      { axis: "Long Passes", value: 75.9 },
      { axis: "Penalty Saves", value: 42.0 },
    ],
  },
]

// Defenders
export const defenders: Player[] = [
  {
    id: "def1",
    player: "Virgil van Dijk",
    team: "Liverpool",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 89.7 },
      { axis: "Aerial Duels Won", value: 92.4 },
      { axis: "Interceptions", value: 85.3 },
      { axis: "Tackles Won", value: 87.1 },
      { axis: "Clearances", value: 91.8 },
      { axis: "Pass Accuracy", value: 94.2 },
      { axis: "Long Balls", value: 88.6 },
    ],
  },
  {
    id: "def2",
    player: "Sergio Ramos",
    team: "PSG",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 86.9 },
      { axis: "Aerial Duels Won", value: 89.3 },
      { axis: "Interceptions", value: 82.7 },
      { axis: "Tackles Won", value: 84.5 },
      { axis: "Clearances", value: 88.2 },
      { axis: "Pass Accuracy", value: 91.8 },
      { axis: "Long Balls", value: 85.4 },
    ],
  },
  {
    id: "def3",
    player: "Ruben Dias",
    team: "Manchester City",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 91.2 },
      { axis: "Aerial Duels Won", value: 88.7 },
      { axis: "Interceptions", value: 89.4 },
      { axis: "Tackles Won", value: 86.8 },
      { axis: "Clearances", value: 90.1 },
      { axis: "Pass Accuracy", value: 95.6 },
      { axis: "Long Balls", value: 87.9 },
    ],
  },
  {
    id: "def4",
    player: "Marquinhos",
    team: "PSG",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 88.4 },
      { axis: "Aerial Duels Won", value: 85.9 },
      { axis: "Interceptions", value: 87.2 },
      { axis: "Tackles Won", value: 83.6 },
      { axis: "Clearances", value: 86.7 },
      { axis: "Pass Accuracy", value: 93.1 },
      { axis: "Long Balls", value: 84.3 },
    ],
  },
  {
    id: "def5",
    player: "Kalidou Koulibaly",
    team: "Chelsea",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 90.6 },
      { axis: "Aerial Duels Won", value: 91.8 },
      { axis: "Interceptions", value: 86.5 },
      { axis: "Tackles Won", value: 88.2 },
      { axis: "Clearances", value: 92.4 },
      { axis: "Pass Accuracy", value: 89.7 },
      { axis: "Long Balls", value: 86.1 },
    ],
  },
  {
    id: "def6",
    player: "Thiago Silva",
    team: "Chelsea",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 87.3 },
      { axis: "Aerial Duels Won", value: 84.6 },
      { axis: "Interceptions", value: 88.9 },
      { axis: "Tackles Won", value: 82.4 },
      { axis: "Clearances", value: 89.5 },
      { axis: "Pass Accuracy", value: 92.8 },
      { axis: "Long Balls", value: 83.7 },
    ],
  },
  {
    id: "def7",
    player: "Mats Hummels",
    team: "Borussia Dortmund",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 85.8 },
      { axis: "Aerial Duels Won", value: 87.2 },
      { axis: "Interceptions", value: 84.1 },
      { axis: "Tackles Won", value: 81.9 },
      { axis: "Clearances", value: 87.6 },
      { axis: "Pass Accuracy", value: 94.3 },
      { axis: "Long Balls", value: 89.2 },
    ],
  },
  {
    id: "def8",
    player: "Raphael Varane",
    team: "Manchester United",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 88.7 },
      { axis: "Aerial Duels Won", value: 90.1 },
      { axis: "Interceptions", value: 85.4 },
      { axis: "Tackles Won", value: 84.8 },
      { axis: "Clearances", value: 88.9 },
      { axis: "Pass Accuracy", value: 91.5 },
      { axis: "Long Balls", value: 85.6 },
    ],
  },
  {
    id: "def9",
    player: "Milan Skriniar",
    team: "PSG",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 89.1 },
      { axis: "Aerial Duels Won", value: 86.4 },
      { axis: "Interceptions", value: 87.8 },
      { axis: "Tackles Won", value: 85.7 },
      { axis: "Clearances", value: 90.3 },
      { axis: "Pass Accuracy", value: 90.9 },
      { axis: "Long Balls", value: 82.8 },
    ],
  },
  {
    id: "def10",
    player: "Antonio Rudiger",
    team: "Real Madrid",
    position: "Defender",
    axes: [
      { axis: "Defensive Actions", value: 87.9 },
      { axis: "Aerial Duels Won", value: 88.5 },
      { axis: "Interceptions", value: 83.6 },
      { axis: "Tackles Won", value: 86.3 },
      { axis: "Clearances", value: 89.7 },
      { axis: "Pass Accuracy", value: 92.4 },
      { axis: "Long Balls", value: 84.1 },
    ],
  },
]

// Midfielders
export const midfielders: Player[] = [
  {
    id: "mid1",
    player: "Pedri",
    team: "FC Barcelona",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 94.1 },
      { axis: "Defensive Actions", value: 37.0 },
      { axis: "Progressive Carries", value: 97.5 },
      { axis: "Forward Passes", value: 95.7 },
      { axis: "Forward Pass Accuracy", value: 52.0 },
      { axis: "Key Passes", value: 95.0 },
      { axis: "Progressive Passes", value: 90.7 },
    ],
  },
  {
    id: "mid2",
    player: "Frenkie de Jong",
    team: "FC Barcelona",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 98.9 },
      { axis: "Defensive Actions", value: 36.3 },
      { axis: "Progressive Carries", value: 97.9 },
      { axis: "Forward Passes", value: 97.7 },
      { axis: "Forward Pass Accuracy", value: 100.0 },
      { axis: "Key Passes", value: 61.4 },
      { axis: "Progressive Passes", value: 85.9 },
    ],
  },
  {
    id: "mid3",
    player: "Kevin De Bruyne",
    team: "Manchester City",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 89.3 },
      { axis: "Defensive Actions", value: 42.8 },
      { axis: "Progressive Carries", value: 92.1 },
      { axis: "Forward Passes", value: 98.4 },
      { axis: "Forward Pass Accuracy", value: 87.6 },
      { axis: "Key Passes", value: 98.7 },
      { axis: "Progressive Passes", value: 94.2 },
    ],
  },
  {
    id: "mid4",
    player: "Luka Modric",
    team: "Real Madrid",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 91.7 },
      { axis: "Defensive Actions", value: 39.5 },
      { axis: "Progressive Carries", value: 89.8 },
      { axis: "Forward Passes", value: 96.2 },
      { axis: "Forward Pass Accuracy", value: 94.1 },
      { axis: "Key Passes", value: 88.9 },
      { axis: "Progressive Passes", value: 92.6 },
    ],
  },
  {
    id: "mid5",
    player: "N'Golo Kanté",
    team: "Chelsea",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 96.4 },
      { axis: "Defensive Actions", value: 89.7 },
      { axis: "Progressive Carries", value: 85.3 },
      { axis: "Forward Passes", value: 88.1 },
      { axis: "Forward Pass Accuracy", value: 78.9 },
      { axis: "Key Passes", value: 72.4 },
      { axis: "Progressive Passes", value: 81.5 },
    ],
  },
  {
    id: "mid6",
    player: "Joshua Kimmich",
    team: "Bayern Munich",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 88.6 },
      { axis: "Defensive Actions", value: 76.2 },
      { axis: "Progressive Carries", value: 91.4 },
      { axis: "Forward Passes", value: 97.8 },
      { axis: "Forward Pass Accuracy", value: 92.3 },
      { axis: "Key Passes", value: 85.7 },
      { axis: "Progressive Passes", value: 96.1 },
    ],
  },
  {
    id: "mid7",
    player: "Marco Verratti",
    team: "PSG",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 93.2 },
      { axis: "Defensive Actions", value: 68.4 },
      { axis: "Progressive Carries", value: 94.7 },
      { axis: "Forward Passes", value: 93.5 },
      { axis: "Forward Pass Accuracy", value: 89.8 },
      { axis: "Key Passes", value: 79.6 },
      { axis: "Progressive Passes", value: 88.3 },
    ],
  },
  {
    id: "mid8",
    player: "Casemiro",
    team: "Manchester United",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 87.9 },
      { axis: "Defensive Actions", value: 92.6 },
      { axis: "Progressive Carries", value: 82.1 },
      { axis: "Forward Passes", value: 89.4 },
      { axis: "Forward Pass Accuracy", value: 84.7 },
      { axis: "Key Passes", value: 68.2 },
      { axis: "Progressive Passes", value: 86.9 },
    ],
  },
  {
    id: "mid9",
    player: "Jude Bellingham",
    team: "Real Madrid",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 90.8 },
      { axis: "Defensive Actions", value: 71.3 },
      { axis: "Progressive Carries", value: 93.6 },
      { axis: "Forward Passes", value: 91.2 },
      { axis: "Forward Pass Accuracy", value: 86.4 },
      { axis: "Key Passes", value: 82.7 },
      { axis: "Progressive Passes", value: 89.5 },
    ],
  },
  {
    id: "mid10",
    player: "Bruno Fernandes",
    team: "Manchester United",
    position: "Midfielder",
    axes: [
      { axis: "Duel %", value: 85.4 },
      { axis: "Defensive Actions", value: 45.9 },
      { axis: "Progressive Carries", value: 88.7 },
      { axis: "Forward Passes", value: 94.3 },
      { axis: "Forward Pass Accuracy", value: 81.2 },
      { axis: "Key Passes", value: 96.8 },
      { axis: "Progressive Passes", value: 91.4 },
    ],
  },
]

// Forwards
export const forwards: Player[] = [
  {
    id: "fwd1",
    player: "Lionel Messi",
    team: "PSG",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 89.7 },
      { axis: "Assists", value: 96.4 },
      { axis: "Shots on Target", value: 92.1 },
      { axis: "Dribbles Completed", value: 98.9 },
      { axis: "Key Passes", value: 97.3 },
      { axis: "Chance Creation", value: 95.8 },
      { axis: "Final Third Entries", value: 94.2 },
    ],
  },
  {
    id: "fwd2",
    player: "Kylian Mbappé",
    team: "PSG",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 94.8 },
      { axis: "Assists", value: 78.6 },
      { axis: "Shots on Target", value: 88.9 },
      { axis: "Dribbles Completed", value: 91.4 },
      { axis: "Key Passes", value: 82.7 },
      { axis: "Chance Creation", value: 85.3 },
      { axis: "Final Third Entries", value: 96.1 },
    ],
  },
  {
    id: "fwd3",
    player: "Erling Haaland",
    team: "Manchester City",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 98.2 },
      { axis: "Assists", value: 65.4 },
      { axis: "Shots on Target", value: 95.7 },
      { axis: "Dribbles Completed", value: 73.8 },
      { axis: "Key Passes", value: 68.9 },
      { axis: "Chance Creation", value: 71.2 },
      { axis: "Final Third Entries", value: 89.6 },
    ],
  },
  {
    id: "fwd4",
    player: "Robert Lewandowski",
    team: "FC Barcelona",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 96.1 },
      { axis: "Assists", value: 74.8 },
      { axis: "Shots on Target", value: 93.4 },
      { axis: "Dribbles Completed", value: 79.2 },
      { axis: "Key Passes", value: 81.6 },
      { axis: "Chance Creation", value: 83.7 },
      { axis: "Final Third Entries", value: 91.3 },
    ],
  },
  {
    id: "fwd5",
    player: "Karim Benzema",
    team: "Al-Ittihad",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 92.6 },
      { axis: "Assists", value: 87.9 },
      { axis: "Shots on Target", value: 89.8 },
      { axis: "Dribbles Completed", value: 84.3 },
      { axis: "Key Passes", value: 89.4 },
      { axis: "Chance Creation", value: 91.7 },
      { axis: "Final Third Entries", value: 88.5 },
    ],
  },
  {
    id: "fwd6",
    player: "Harry Kane",
    team: "Bayern Munich",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 91.4 },
      { axis: "Assists", value: 82.3 },
      { axis: "Shots on Target", value: 87.6 },
      { axis: "Dribbles Completed", value: 76.8 },
      { axis: "Key Passes", value: 85.9 },
      { axis: "Chance Creation", value: 88.2 },
      { axis: "Final Third Entries", value: 86.7 },
    ],
  },
  {
    id: "fwd7",
    player: "Neymar Jr",
    team: "Al-Hilal",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 86.9 },
      { axis: "Assists", value: 93.7 },
      { axis: "Shots on Target", value: 84.2 },
      { axis: "Dribbles Completed", value: 96.8 },
      { axis: "Key Passes", value: 94.1 },
      { axis: "Chance Creation", value: 97.4 },
      { axis: "Final Third Entries", value: 92.8 },
    ],
  },
  {
    id: "fwd8",
    player: "Mohamed Salah",
    team: "Liverpool",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 89.3 },
      { axis: "Assists", value: 79.6 },
      { axis: "Shots on Target", value: 91.7 },
      { axis: "Dribbles Completed", value: 87.4 },
      { axis: "Key Passes", value: 83.8 },
      { axis: "Chance Creation", value: 86.5 },
      { axis: "Final Third Entries", value: 94.9 },
    ],
  },
  {
    id: "fwd9",
    player: "Vinicius Jr",
    team: "Real Madrid",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 84.7 },
      { axis: "Assists", value: 81.2 },
      { axis: "Shots on Target", value: 82.9 },
      { axis: "Dribbles Completed", value: 94.6 },
      { axis: "Key Passes", value: 78.4 },
      { axis: "Chance Creation", value: 82.1 },
      { axis: "Final Third Entries", value: 97.3 },
    ],
  },
  {
    id: "fwd10",
    player: "Sadio Mané",
    team: "Al-Nassr",
    position: "Forward",
    axes: [
      { axis: "Goals per Game", value: 87.8 },
      { axis: "Assists", value: 76.9 },
      { axis: "Shots on Target", value: 85.4 },
      { axis: "Dribbles Completed", value: 89.1 },
      { axis: "Key Passes", value: 80.7 },
      { axis: "Chance Creation", value: 84.6 },
      { axis: "Final Third Entries", value: 90.2 },
    ],
  },
]

export const allPlayers = [...goalkeepers, ...defenders, ...midfielders, ...forwards]

export const getPlayersByPosition = (position: Player["position"]) => {
  switch (position) {
    case "Goalkeeper":
      return goalkeepers
    case "Defender":
      return defenders
    case "Midfielder":
      return midfielders
    case "Forward":
      return forwards
    default:
      return []
  }
}
